---
name: "Filmaffinity"
guid: "86d2dfbb-e99d-4b1f-b249-9a5aa707a338"
version: "1.0.0.0"
targetAbi: "10.9.5.0"
framework: "net8.0"
overview: "Get metadata from Filmaffinity"
description: >
  Get TV and movies metadata from Filmaffinity
category: "Metadata"
owner: "markstor"
artifacts:
- "Jellyfin.Plugin.Filmaffinity.dll"
changelog: >
  changelog
